ansible_user: "{{ vault_ansible_user }}"
ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"
db_login_user: "{{ lookup('env', 'DB_LOGIN_USER') }}"
db_login_password: "{{ lookup('env', 'DB_LOGIN_PASSWORD') }}"
db_ssl_mode: require
