postgresql_version: 13
postgresql_configuration_directory: /var/lib/pgsql/{{ postgresql_version }}/data
max_connections: 100
shared_buffers: 128MB
random_page_cost: 4.0
hoh_db: hoh
hoh_process_user: hoh_process_user
transport_bridge_user: transport_bridge_user
spec_schema: spec
status_schema: status
local_spec_schema: local_spec
local_status_schema: local_status
history_schema: history
# according to Kubernetes DNS label standard https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
cluster_name_length_limit: 63
managed_clusters_table: managed_clusters
policies_table: compliance
aggregated_policies_table: aggregated_compliance
leaf_hub_heartbeats_table: leaf_hub_heartbeats
subscriptions_table: subscriptions
clusterdeployments_table: clusterdeployments
secrets_table: secrets
enforcement_type: enforcement_type
compliance_type: compliance_type
error_type: error_type
set_timestamp_trigger: set_timestamp
move_to_history_trigger: move_to_history
vault_ansible_user: ec2-user
vault_ansible_ssh_private_key_file: /Users/ianzhang/9bin/izhang-far-edge.cer