---
- name: create table {{ name }} schema {{ schema }} database {{ database }}
  tags: tables
  postgresql_table:
    table: "{{ schema }}.{{ name }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns:
      - id uuid primary key
      - payload jsonb not null
      - created_at timestamp not null default now()
      - updated_at timestamp not null default now()
      - deleted boolean not null default false


  # based on https://x-team.com/blog/automatic-timestamps-with-postgresql/
- name: add timestamp trigger
  tags: tables
  vars:
    table: "{{ name }}"
  include_tasks: create_timestamp_trigger.yaml

- name: add move_to_history trigger
  tags: tables
  vars:
    table: "{{ name }}"
  include_tasks: create_move_to_history_trigger.yaml
  when: schema != history_schema
