---
- name: create spec tables
  tags: tables
  vars:
    database: "{{ hoh_db }}"
  include_tasks: create_spec_table.yaml
  loop:
    - policies
    - placementrules
    - placementbindings
    - configs
    - subscriptions
    - channels
    - applications
    - clusterdeployments
    - secrets
    - machinepools
    - klusterletaddonconfigs
  loop_control:
    loop_var: name

- name: create managed-clusters metadata table
  postgresql_table:
    table: "{{ spec_schema }}.{{ managed_clusters_metadata_table }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns:
      - leaf_hub_name         varchar({{ cluster_name_length_limit }}) not null
      - managed_cluster_name  varchar({{ cluster_name_length_limit }}) not null
      - labels                text not null
      - deleted_label_keys    text not null  default ""
      - version               bigint not null check (version > 0)

- name: create index on version
  postgresql_idx:
    name: "{{ managed_clusters_metadata_table }}_version_idx"
    table: "{{ managed_clusters_metadata_table }}"
    schema: "{{ spec_schema }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns: "version"
    idxtype: btree
    unique: false
