---
- name: create table {{ schema }}.{{ policies_table }}
  postgresql_table:
    name: "{{ schema }}.{{ policies_table }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns:
      - id uuid not null
      - cluster_name varchar({{ cluster_name_length_limit }}) not null
      - leaf_hub_name varchar({{ cluster_name_length_limit }}) not null
      - error {{ status_schema }}.{{ error_type }} not null
      - compliance {{ status_schema }}.{{ compliance_type }} not null


- name: create index on leaf_hub_name and compliance
  postgresql_idx:
    name: "{{ policies_table }}_leaf_hub_non_compliant_idx"
    table: "{{ policies_table }}"
    schema: "{{ status_schema }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns: leaf_hub_name, compliance
    cond: compliance != 'compliant'


- name: create index on id and compliance
  postgresql_idx:
    name: "{{ policies_table }}_id_non_compliant_idx"
    table: "{{ policies_table }}"
    schema: "{{ status_schema }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns: id, compliance
    cond: compliance != 'compliant'


- name: create index on leaf_hub_name and cluster_name
  postgresql_idx:
    name: "{{ policies_table }}_leaf_hub_cluster_idx"
    table: "{{ policies_table }}"
    schema: "{{ status_schema }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns: leaf_hub_name, cluster_name

- name: create index on id, leaf_hub_name, cluster_name
  postgresql_idx:
    name: "{{ policies_table }}_policy_leaf_hub_cluster_idx"
    table: "{{ policies_table }}"
    schema: "{{ status_schema }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns: id, leaf_hub_name, cluster_name
    unique: yes

- name: create index on leaf_hub_name, id
  postgresql_idx:
    name: "{{ policies_table }}_leaf_hub_id_idx"
    table: "{{ policies_table }}"
    schema: "{{ status_schema }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns: leaf_hub_name, cluster_name, id
    unique: yes

