---
- name: create managed clusters metadata table
  tags: tables
  postgresql_table:
    table: "{{ schema }}.{{ name }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns:
      - managed_cluster_name  varchar({{ cluster_name_length_limit }}) not null
      - labels                jsonb not null default '[]'::jsonb  # format: array of {"key":"k","value":"v"}
      - deleted_label_keys    jsonb not null default '[]'::jsonb  # format: array of strings
      - version               timestamp not null default now()

- name: create index on version
  postgresql_idx:
    name: "{{ name }}_version_idx"
    table: "{{ name }}"
    schema: "{{ schema }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns: "version"
    idxtype: btree
    unique: false
