---
- name: create managed_clusters_labels table
  tags: tables
  postgresql_table:
    table: "{{ schema }}.{{ name }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns:
      - leaf_hub_name         varchar({{ cluster_name_length_limit }}) not null default ''
      - managed_cluster_name  varchar({{ cluster_name_length_limit }}) not null
      - labels                jsonb not null default '{}'::jsonb  # format: array of {"key":"value"}
      - deleted_label_keys    jsonb not null default '[]'::jsonb  # format: array of strings
      - updated_at            timestamp not null default now()
      - version               bigint not null default 0 check (version >= 0) # version field local for each row

- name: create index on updated_at
  postgresql_idx:
    name: "{{ name }}_updated_at_idx"
    table: "{{ name }}"
    schema: "{{ schema }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns: "updated_at"
    idxtype: btree
    unique: false

- name: create index on leaf_hub_name, managed_cluster_name, version
  postgresql_idx:
    name: "{{ name }}_updated_at_idx"
    table: "{{ name }}"
    schema: "{{ schema }}"
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    columns: "updated_at, managed_cluster_name, version"
    idxtype: btree
    unique: false
