---
# based on https://x-team.com/blog/automatic-timestamps-with-postgresql/
- name: create set_timestamp trigger
  tags: tables
  postgresql_query:
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    # transaction logic based on https://stackoverflow.com/a/61974663/553720
    query: |
      DO $$
      BEGIN
        IF NOT EXISTS(SELECT 1
          FROM pg_trigger
          WHERE tgrelid = '{{schema}}.{{ table }}'::regclass
          AND tgname = '{{ set_timestamp_trigger }}'
        )
        THEN
          CREATE TRIGGER {{ set_timestamp_trigger }}
          BEFORE UPDATE ON {{ schema }}.{{ table }}
          FOR EACH ROW
          EXECUTE PROCEDURE trigger_set_timestamp();
        END IF;
      END;
      $$

