---
- name: create local spec tables
  tags: tables
  vars:
    database: "{{ hoh_db }}"
  include_tasks: create_local_spec_table.yaml
  loop:
    - policies
    - placementrules
  loop_control:
    loop_var: name
