apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
  namespace: hoh-postgres
spec:
  template:
    spec:
      containers:
      - name: initial-db
        env:
          - name: ANSIBLE_PYTHON_INTERPRETER
            value: "/usr/bin/python2"
          - name: DB_LOGIN_HOST
            valueFrom:
              secretKeyRef:
                name: hoh-pguser-hoh-process-user
                key: host
          - name: DB_LOGIN_USER
            valueFrom:
              secretKeyRef:
                name: hoh-pguser-hoh-process-user
                key: user
          - name: DB_LOGIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hoh-pguser-hoh-process-user
                key: password
        image: quay.io/ianzhang366/postgre-ansible:latest
        command: ["/bin/bash", "-c", "ansible-playbook pgo.yaml -i production -l local"]
      restartPolicy: Never
  backoffLimit: 3

