---
- name: create hoh process user
  postgresql_user:
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    name: "{{ hoh_process_user }}"
  become: yes
  become_user: postgres

- name: create transport bridge user
  postgresql_user:
    db: "{{ hoh_db }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    ssl_mode: "{{ db_ssl_mode }}"
    name: "{{ transport_bridge_user }}"
  become: yes
  become_user: postgres
