---
- name: create table {{ name }} schema {{ schema }} database {{ database }}
  tags: tables
  postgresql_table:
    name: "{{ status_schema }}.{{ name }}"
    db: "{{ database }}"
    columns:
      - id uuid not null
      - leaf_hub_name varchar({{ cluster_name_length_limit }}) not null
      - payload jsonb not null
  become: yes
  become_user: postgres

- name: create index on payload->'metadata'->>'name' for table {{ name }}
  postgresql_idx:
    name: "{{ name }}_metadata_name_idx"
    table: "{{ name }}"
    schema: "{{ status_schema }}"
    db: "{{ database }}"
    columns: "(payload->'metadata'->>'name')"
    idxtype: btree
    unique: true
  become: yes
  become_user: postgres

- name: create index on payload->'metadata'->>'namespace'  for table {{ name }}
  postgresql_idx:
    name: "{{ name }}_metadata_namespace_idx"
    table: "{{ name }}"
    schema: "{{ status_schema }}"
    db: "{{ database }}"
    columns: "(payload->'metadata'->>'namespace')"
    idxtype: btree
    unique: true
  become: yes
  become_user: postgres